name: pragmatic
description: A simple command-line application.
version: 0.0.1
homepage: https://github.com/dartsidedev/pragmatic
repository: https://github.com/dartsidedev/pragmatic
issue_tracker: https://github.com/dartsidedev/pragmatic/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
